-- Dragon Follow Base Boss

require "botWorker"
require "basic"
function GetBotWorker()
	local bW = BotWorker('54_BossA')
	--bW:KillMobByName('Punisher Brass')
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	bW:KillMobByNameHP('Punisher Brass')
	bW:AddMobToIgnoreList(1, 'Punisher Brass')
	bW:KillMobs(10000)
	bW:RemoveMobFromIgnoreList(1)
	--bW:Finish()

	return bW
end 