-- Spirit Grave Tomb Map 3

require "botWorker"
require "basic"
function GetBotWorker()
	local bW = BotWorker('55_BossA')
	bW:WalkTo(-75, 109, -251)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
		bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Wait(2000)
	bW:UseLastSpawnedProp()
	bW:Wait(2000)
	--bW:KillMobByName('Great Mimic Dalton')
	bW:KillMobs(2000)
	bW:Finish()

  return bW
end
